version: '1.0'

services:
  web:
    build: .
    container_name: web_django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/local/app
    depends_on:
      - db
      - redis

  db:
    image: postgres
    container_name: postgres_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=localpassword
    volumes:
      - pg_data:/var/lib/postgres/data
  
  redis:
    image: redis
    container_name: redis_db
    volumes:
      - redis_data:/var/lib/redis/data 
volumes:
  pg_data: null
  redis_data: null