version: '1.0'

services:
  web:
    build: .
    container_name: web_django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/local/app
    depends_on:
      - db
      - redis
      - elastic

  db:
    image: postgres
    container_name: postgres_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=localpassword
    volumes:
      - pg_data:/var/lib/postgres/data
  
  redis:
    image: redis
    container_name: redis_db
    volumes:
      - redis_data:/var/lib/redis/data 
  
  elastic:
    image: elasticsearch:8.2.0
    container_name: elastic_search
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/var/lib/elastic/data
volumes:
  pg_data: null
  redis_data: null
  elastic_data: null