# Generated by Django 4.0.4 on 2022-05-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tag_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='post_tags', to='app.tag', verbose_name='Теги'),
        ),
    ]
